services:
  # バックエンドサービス (FastAPI)
  backend:
    build: ./backend
    container_name: stripe-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - stripe-network
    restart: unless-stopped

  # フロントエンドサービス (React + TypeScript)
  frontend:
    build: ./frontend
    container_name: stripe-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - stripe-network
    restart: unless-stopped

  # Redis (セッション管理用 - 将来拡張)
  redis:
    image: redis:7-alpine
    container_name: stripe-redis
    ports:
      - "6379:6379"
    networks:
      - stripe-network
    restart: unless-stopped

networks:
  stripe-network:
    driver: bridge

volumes:
  node_modules:
  backend_cache:
